version: '{build}'
image:
- Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/
init:
- cmd: dotnet --info
- sh: dotnet --info
build_script:
- cmd: ./build.cmd
test: off
artifacts:
- path: ./**/*.nupkg
deploy: off
