version: '{build}'
environment:
  APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG: true
image:
- Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - /release-.*/
init:
- cmd: dotnet --info
build_script:
- cmd: ./build.cmd
test: off
artifacts:
- path: ./**/bin/Release/*.nupkg
deploy: off
