on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '*.*.*'
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-16.04, ubuntu-latest, windows-2016, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/setup-dotnet@b7821147f564527086410e8edd122d89b4b9602f
      with:
        dotnet-version: '3.1.300'
    - run: dotnet --info
    - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
    - if: contains(matrix.runs-on, 'windows')
      env:
        VERSION: ${{ secrets.VERSION }}
      run: ./build.cmd
    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      env:
        VERSION: ${{ secrets.VERSION }}
      run: ./build.sh
    - if: matrix.runs-on == 'ubuntu-latest'
      env:
        MYGET_ADAMRALPH_CI_API_KEY: ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
      run: ./push.sh
