name: ci
on:
  push:
    branches: [main, release-*]
    tags: ["*.*.*"]
  pull_request:
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job:
              os: macos-10.15
              build: ./build.sh
            tests:
              framework: net6.0
              sdk: "6.0.101"
          - job:
              os: macos-11
              build: ./build.sh
            tests:
              framework: net5.0
              sdk: "5.0.404"
          - job:
              os: macos-11
              build: ./build.sh
            tests:
              framework: net6.0
              sdk: "6.0.101"
          - job:
              os: ubuntu-18.04
              build: ./build.sh
            tests:
              framework: net6.0
              sdk: "6.0.101"
          - job:
              os: ubuntu-20.04
              build: ./build.sh
            tests:
              framework: netcoreapp3.1
              sdk: "3.1.416"
          - job:
              os: ubuntu-20.04
              build: ./build.sh
            tests:
              framework: net5.0
              sdk: "5.0.404"
          - job:
              os: ubuntu-20.04
              build: ./build.sh
              push: true
            tests:
              framework: net6.0
              sdk: "6.0.101"
          - job:
              os: windows-2019
              build: ./build.cmd
            tests:
              framework: net6.0
              sdk: "6.0.101"
          - job:
              os: windows-2022
              build: ./build.cmd
            tests:
              framework: net5.0
              sdk: "5.0.404"
          - job:
              os: windows-2022
              build: ./build.cmd
            tests:
              framework: net6.0
              sdk: "6.0.101"
    name: ${{ matrix.job.os }}-${{ matrix.tests.framework }}
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |
            ${{ matrix.tests.sdk }}
            6.0.101
      - run: dotnet --info
      - uses: actions/checkout@v2.4.0
      - env:
          CI_VERSION: ${{ secrets.CI_VERSION }}
          MINVER_TESTS_SDK: ${{ matrix.tests.sdk }}
          MINVER_TESTS_FRAMEWORK: ${{ matrix.tests.framework }}
        run: ${{ matrix.job.build }}
      - name: push
        env:
          API_KEY: ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
        if: ${{ matrix.job.push && env.API_KEY != '' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
        run: |
          dotnet nuget push MinVer/**/*.nupkg --source https://www.myget.org/F/adamralph-ci/api/v2/package --api-key ${{ env.API_KEY }}
          dotnet nuget push minver-cli/**/*.nupkg --source https://www.myget.org/F/adamralph-ci/api/v2/package --api-key ${{ env.API_KEY }}
