on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '*.*.*'
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-10.15, ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/setup-dotnet@6efb2bd78f16e08562660f8246d6bd76adf6281f
      with:
        dotnet-version: '3.1.301'
    - run: dotnet --info
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - if: contains(matrix.runs-on, 'windows')
      env:
        VERSION: ${{ secrets.VERSION }}
      run: ./build.cmd
    - if: contains(matrix.runs-on, 'macos') || contains(matrix.runs-on, 'ubuntu')
      env:
        VERSION: ${{ secrets.VERSION }}
      run: ./build.sh
    - if: matrix.runs-on == 'ubuntu-18.04'
      env:
        MYGET_ADAMRALPH_CI_API_KEY: ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
      run: ./push.sh
