on:
  push:
    branches: [master, release-*]
    tags: ["*.*.*"]
  pull_request:
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: macos-10.15
            build: ./build.sh
          - os: ubuntu-16.04
            build: ./build.sh
          - os: ubuntu-18.04
            build: ./build.sh
            push: true
          - os: windows-2016
            build: ./build.cmd
          - os: windows-2019
            build: ./build.cmd
        tests:
          - sdk: 2.1.300
            framework: netcoreapp2.1
          - sdk: 2.1.811
            framework: netcoreapp2.1
          - sdk: 3.1.100
            framework: netcoreapp3.1
          - sdk: 3.1.404
            framework: netcoreapp3.1
          - sdk: 5.0.100
            framework: net5.0
            push: true
    name: ${{ matrix.job.os }}-${{ matrix.tests.sdk }}
    runs-on: ${{ matrix.job.os }}
    steps:
      - name: setup-dotnet tests-sdk
        if: matrix.tests.sdk != '5.0.100'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "${{ matrix.tests.sdk }}"
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "5.0.100"
      - run: dotnet --info
      - uses: actions/checkout@v2.3.4
      - env:
          CI_VERSION: ${{ secrets.CI_VERSION }}
          MINVER_TESTS_SDK: ${{ matrix.tests.sdk }}
          MINVER_TESTS_FRAMEWORK: ${{ matrix.tests.framework }}
        run: ${{ matrix.job.build }}
      - name: push
        env:
          API_KEY: ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
        if: matrix.job.push && matrix.tests.push && env.API_KEY != ''
        run: |
          dotnet nuget push MinVer/**/*.nupkg --source https://www.myget.org/F/adamralph-ci/api/v2/package --api-key ${{ env.API_KEY }}
          dotnet nuget push minver-cli/**/*.nupkg --source https://www.myget.org/F/adamralph-ci/api/v2/package --api-key ${{ env.API_KEY }}
