name: ci
on:
  push:
    branches: [main, release-*]
  pull_request:
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job:
              os: macos-10.15
            tests:
              framework: net6.0
              sdk: "6.0.300"
              sdk-major-minor: "6.0"
          - job:
              os: macos-11
            tests:
              framework: net6.0
              sdk: "6.0.300"
              sdk-major-minor: "6.0"
          - job:
              os: macos-11
            tests:
              framework: net6.0
              sdk: "7.0.100-preview.4.22252.9"
              sdk-major-minor: "7.0"
          - job:
              os: ubuntu-18.04
            tests:
              framework: net6.0
              sdk: "6.0.300"
              sdk-major-minor: "6.0"
          - job:
              os: ubuntu-20.04
            tests:
              framework: netcoreapp3.1
              sdk: "3.1.419"
              sdk-major-minor: "3.1"
          - job:
              os: ubuntu-20.04
              upload: true
            tests:
              framework: net6.0
              sdk: "6.0.300"
              sdk-major-minor: "6.0"
          - job:
              os: ubuntu-20.04
            tests:
              framework: net6.0
              sdk: "7.0.100-preview.4.22252.9"
              sdk-major-minor: "7.0"
          - job:
              os: windows-2019
            tests:
              framework: net6.0
              sdk: "6.0.300"
              sdk-major-minor: "6.0"
          - job:
              os: windows-2022
            tests:
              framework: net6.0
              sdk: "6.0.300"
              sdk-major-minor: "6.0"
          - job:
              os: windows-2022
            tests:
              framework: net6.0
              sdk: "7.0.100-preview.4.22252.9"
              sdk-major-minor: "7.0"
    name: ${{ matrix.job.os }}-sdk-${{ matrix.tests.sdk-major-minor }}
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: |
            ${{ matrix.tests.sdk }}
            6.0.300
      - run: dotnet --info
      - run: git --version
      - uses: actions/checkout@v3.0.2
      - env:
          CI_NUMBER: ${{ github.run_number }}
          MINVER_VERSION: ${{ secrets.MINVER_VERSION }}
          MINVER_TESTS_SDK: ${{ matrix.tests.sdk }}
          MINVER_TESTS_FRAMEWORK: ${{ matrix.tests.framework }}
        run: ./build
      - if: matrix.job.upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: NuGet packages
          path: ./**/*.nupkg
