on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '*.*.*'
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-10.14, ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/setup-dotnet@6c0e2a2a6b8dbd557c411f0bd105b341d4ce40d2
      with:
        dotnet-version: '3.0.100-preview9-014004'
    - run: dotnet --info
    - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
    - if: contains(matrix.runs-on, 'windows')
      env:
        VERSION: ${{ secrets.VERSION }}
      run: build.cmd
    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      env:
        VERSION: ${{ secrets.VERSION }}
      run: ./build.sh
    - if: matrix.runs-on == 'ubuntu-18.04'
      run: ./push.sh ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
