on:
  push:
    branches: [master]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx markdownlint-cli2 "**/*.md" "#node_modules"
