name: release
on:
  push:
    tags: ["*.*.*"]
permissions: read-all
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 9.0.200
      - uses: actions/checkout@v4.2.2
      - env:
          MINVER_VERSION: ${{ vars.MINVER_VERSION }}
        run: ./build build
      - name: push
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
